// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package counter

import (
	"github.com/namnv2496/go-coffee-shop-demo/internal/counter/app"
	"github.com/namnv2496/go-coffee-shop-demo/internal/counter/handler/jobs"
	"github.com/namnv2496/go-coffee-shop-demo/internal/counter/handler/router"
	"github.com/namnv2496/go-coffee-shop-demo/internal/counter/repo"
	"github.com/namnv2496/go-coffee-shop-demo/internal/counter/service"
	"github.com/namnv2496/go-coffee-shop-demo/pkg/cache"
	"github.com/namnv2496/go-coffee-shop-demo/pkg/configs"
	"github.com/namnv2496/go-coffee-shop-demo/pkg/data_access"
	"github.com/namnv2496/go-coffee-shop-demo/pkg/mq/producer"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func Initialize(grpc2 *grpc.Server, filePath configs.ConfigFilePath) (*app.App, func(), error) {
	config, err := configs.GetConfigFromYaml(filePath)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := database.InitializeAndMigrateUpDB(config)
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	orderRepo := repo.NewOrderRepo(goquDatabase)
	customerRepo := repo.NewCustomerRepo(goquDatabase)
	redis := config.Redis
	client := cache.NewRedisClient(redis)
	orderService := service.NewOrderService(orderRepo, customerRepo, client)
	productGRPCClient, err := router.NewGRPCProductClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	producerClient := producer.NewClient(config)
	clearAllOrderEOD := jobs.NewExecuteClearAllOrderEOD(orderService)
	cron := config.Cron
	appApp := app.NewApp(orderService, productGRPCClient, producerClient, clearAllOrderEOD, cron)
	return appApp, func() {
		cleanup()
	}, nil
}
