// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package author

import (
	"github.com/namnv2496/go-coffee-shop-demo/internal/authorization/app"
	"github.com/namnv2496/go-coffee-shop-demo/internal/authorization/repo"
	"github.com/namnv2496/go-coffee-shop-demo/internal/authorization/service"
	"github.com/namnv2496/go-coffee-shop-demo/pkg/configs"
	"github.com/namnv2496/go-coffee-shop-demo/pkg/data_access"
)

// Injectors from wire.go:

func Initialize(filePath configs.ConfigFilePath) (*app.App, func(), error) {
	config, err := configs.GetConfigFromYaml(filePath)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := database.InitializeAndMigrateUpDB(config)
	if err != nil {
		return nil, nil, err
	}
	goquDatabase := database.InitializeGoquDB(db)
	userRepo := repo.NewUserRepo(goquDatabase)
	userService := service.NewUserService(userRepo)
	appApp := app.NewApp(userService)
	return appApp, func() {
		cleanup()
	}, nil
}
